language: go
dist: xenial
addons:
  snaps:
  - name: hugo
    channel: extended

install:
  - sudo pip install s3cmd

script:
  - hugo --minify --verbose
  - s3cmd --region=ap-southeast-2 sync --delete-removed -P --guess-mime-type --no-mime-magic -r public/ s3://mikerowecode.com/
notifications:
    email:
        on_failure: always
